server:
  port: 8081

spring:
  application:
    name: recipe
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/recipes
    password: ldishes
    username: ldishes
    name: ldishes
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        auto-index-creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
